[package]
name = "squashfs-rc4"
version = "0.1.0"
edition = "2024"

[dependencies]
backhand = "0.21.0"
clap = { version = "4.5.32", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
